Have you created the S3 buckets yet? [y/n] Creating the Input and Output S3 buckets and folders within
Traceback (most recent call last):
  File "/home/ubuntu/weCloudProject/Create_AWS_Artifacts/create_s3_buckets.py", line 26, in <module>
    s3_client.create_bucket(
  File "/usr/lib/python3/dist-packages/botocore/client.py", line 553, in _api_call
    return self._make_api_call(operation_name, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/botocore/client.py", line 1009, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (IllegalLocationConstraintException) when calling the CreateBucket operation: The {Same as your EC2 Instance Region} location constraint is incompatible for the region specific endpoint this request was sent to.
Failed to create the S3 buckets
[ERROR:] RETURN CODE:  1
[ERROR:] REFER TO THE LOG FOR THE REASON FOR THE FAILURE.
